/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("UraProductRegListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheUraProductRegListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheUraProductRegListGenerated.onFilterBar().iCheckFilterField({ property: "CompanyCode" });
            Then.onTheUraProductRegListGenerated.onFilterBar().iCheckFilterField({ property: "GoodsCode" });
            Then.onTheUraProductRegListGenerated.onFilterBar().iCheckFilterField({ property: "Description" });
            Then.onTheUraProductRegListGenerated.onFilterBar().iCheckFilterField({ property: "CommodityCategoryId" });
            Then.onTheUraProductRegListGenerated.onFilterBar().iCheckFilterField({ property: "MaterialType" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheUraProductRegListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheUraProductRegListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheUraProductRegListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheUraProductRegListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheUraProductRegListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheUraProductRegListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheUraProductRegListGenerated.onTable(defaultTableId).iPressAction("Post to EFRIS");
            Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckAction("Post to EFRIS", { enabled: false });
            // When.onTheUraProductRegListGenerated.onTable(defaultTableId).iPressAction("Fetch Candidates");
            Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckAction("Fetch Candidates", { enabled: true });
            Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Status":{"header":"Status"},"ResultMsg":{"header":"Result Message"},"GoodsCode":{"header":"Material"},"Description":{"header":"Description"},"CommodityCategoryId":{"header":"Commodity Catgy ID"},"CommodityCategoryDesc":{"header":"Commodity Catgy Desc"},"EfrisUom":{"header":"Customs Pack Units"},"SapUom":{"header":"Base Unit of Measure"},"PieceMeasureUnit":{"header":"Customs Piece Units"},"MaterialType":{"header":"Material Type"},"HaveExciseTax":{"header":"Have Excise Tax"},"HavePieceUnit":{"header":"Have Piece Unit"},"HaveOtherUnit":{"header":"Have Other Unit"},"SAPAunUnits":{"header":"SAPAunUnits"},"EFRISAunUnits":{"header":"EFRISAunUnits"},"StockPrewarning":{"header":" Stock Prewarning"},"UnitPrice":{"header":"Unit Price"},"Currency":{"header":"Currency"},"Weight":{"header":"SAP Net Weight"},"PieceUnitPrice":{"header":"Piece Unit Price"},"PackageScaledValue":{"header":"Package Scaled Value"},"PieceScaledValue":{"header":"Piece Scaled Value"},"ResultDate":{"header":"Resultdt"},"ResultTime":{"header":"Result Time"},"ResultCode":{"header":"Result Code"},"CreatedBy":{"header":"Created By"},"CreatedByName":{"header":"Created by name"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheUraProductRegListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheUraProductRegListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheUraProductRegListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheUraProductRegObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});