/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("UraProductRegObjectPageObjectPage journey");

        opaTest("Navigate to UraProductRegObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheUraProductRegListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheUraProductRegListGenerated.onTable().iCheckRows();
            When.onTheUraProductRegListGenerated.onTable().iPressRow(0);

            Then.onTheUraProductRegObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the ProductDetails section of the Object Page", function (_Given, _When, Then) {
            Then.onTheUraProductRegObjectPageGenerated.iCheckSection({ section: "ProductDetails" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "Status" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "ResultMsg" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "GoodsCode" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "Description" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "CommodityCategoryId" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "CommodityCategoryDesc" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "EfrisUom" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "SapUom" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PieceMeasureUnit" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "MaterialType" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "HaveExciseTax" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "HavePieceUnit" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "HaveOtherUnit" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "SAPAunUnits" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "EFRISAunUnits" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "StockPrewarning" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "UnitPrice" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "Currency" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "Weight" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PieceUnitPrice" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PackageScaledValue" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PieceScaledValue" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "ResultDate" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "ResultTime" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "ResultCode" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "CreatedBy" });
            Then.onTheUraProductRegObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "CreatedByName" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});